# ============================================================================
# COACHING_TIPS REPOSITORY
# ============================================================================
# This file was auto-generated on: 2026-01-06 22:00:46 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.coaching_tips import CoachingTipsUpdate, CoachingTipsCreate, CoachingTipsOut

async def create_coaching_tips(coaching_tips_data: CoachingTipsCreate) -> CoachingTipsOut:
    coaching_tips_dict = coaching_tips_data.model_dump()
    result =await db.coaching_tipss.insert_one(coaching_tips_dict)
    result = await db.coaching_tipss.find_one(filter={"_id":result.inserted_id})
    returnable_result = CoachingTipsOut(**result)
    return returnable_result

async def get_coaching_tips(filter_dict: dict) -> Optional[CoachingTipsOut]:
    try:
        result = await db.coaching_tipss.find_one(filter_dict)

        if result is None:
            return None

        return CoachingTipsOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching coaching_tips: {str(e)}"
        )
    
async def get_coaching_tipss(filter_dict: dict = {},start=0,stop=100) -> List[CoachingTipsOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.coaching_tipss.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        coaching_tips_list = []

        async for doc in cursor:
            coaching_tips_list.append(CoachingTipsOut(**doc))

        return coaching_tips_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching coaching_tipss: {str(e)}"
        )
async def update_coaching_tips(filter_dict: dict, coaching_tips_data: CoachingTipsUpdate) -> CoachingTipsOut:
    result = await db.coaching_tipss.find_one_and_update(
        filter_dict,
        {"$set": coaching_tips_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = CoachingTipsOut(**result)
    return returnable_result

async def delete_coaching_tips(filter_dict: dict):
    return await db.coaching_tipss.delete_one(filter_dict)