# ============================================================================
# SETTINGS REPOSITORY
# ============================================================================
# This file was auto-generated on: 2026-01-07 10:53:34 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.settings import SettingsUpdate, SettingsCreate, SettingsOut

async def create_settings(settings_data: SettingsCreate) -> SettingsOut:
    settings_dict = settings_data.model_dump()
    result =await db.settingss.insert_one(settings_dict)
    result = await db.settingss.find_one(filter={"_id":result.inserted_id})
    returnable_result = SettingsOut(**result)
    return returnable_result

async def get_settings(filter_dict: dict) -> Optional[SettingsOut]:
    try:
        result = await db.settingss.find_one(filter_dict)

        if result is None:
            return None

        return SettingsOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching settings: {str(e)}"
        )
    
async def get_settingss(filter_dict: dict = {},start=0,stop=100) -> List[SettingsOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.settingss.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        settings_list = []

        async for doc in cursor:
            settings_list.append(SettingsOut(**doc))

        return settings_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching settingss: {str(e)}"
        )
async def update_settings(filter_dict: dict, settings_data: SettingsUpdate) -> SettingsOut:
    result = await db.settingss.find_one_and_update(
        filter_dict,
        {"$set": settings_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = SettingsOut(**result)
    return returnable_result

async def delete_settings(filter_dict: dict):
    return await db.settingss.delete_one(filter_dict)